name: Healthcheck (Lint + Unit Test)

on:
  pull_request:
    branches:
      - main

jobs:
  healthcheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v3
      - name: 'Setup Node.js | Node Version: ${{ matrix.node-version }}'
        continue-on-error: true
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            deps-node-modules-
      - name: Install dependencies
        run: npm ci
      - name: Runs linter
        run: npm run lint
      - name: Runs unit test
        run: npm run test
